### model
model_name_or_path: /workspace/acl/model_zoo/llama/llama-2-7b-hf

### method
stage: sft
do_train: true
finetuning_type: lora


### dataset
dataset: identity,alpaca_en_demo
dataset_dir: /workspace/acl/datasets
template: llama2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: /workspace/acl/saves/adapters/lora/llama2-7b-hf
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
load_best_model_at_end: true
max_length: 1024
max_new_tokens: 1024


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0

optim: adamw_hf

lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
ddp_timeout: 180000000

### lora
lora_rank: 8
lora_dropout: 0.0
lora_target: all


### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
