### model
model_name_or_path: /workspace/acl/model_zoo/llama/llama-2-7b-hf
adapter_name_or_path: /workspace/acl/saves/adapters/lora/llama2-7b-hf
template: llama2
finetuning_type: lora

### export
export_dir: /workspace/acl/saves/models/llama2-7b-hf
export_size: 2
export_device: cpu
export_legacy_format: false
